apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: square-api
spec:
  type: bindings.http
  version: v1
  metadata:
    - name: url
      value: https://connect.squareupsandbox.com/
    - name: securityToken
      value: Bearer EAAAl-FIuAfmE-ToAy4nZ-w71KSeWrxhbX1g-jmWiuIQ4knDVot4c8XDr-Y4hKcZ
    - name: securityTokenHeader
      value: Authorization
scopes:
  - payments
