apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: square-api
spec:
  type: bindings.http
  version: v1
  metadata:
    - name: url
      value: https://connect.squareupsandbox.com/
    - name: securityToken
      secretKeyRef:
        name: squareToken
        key: squareToken
    - name: securityTokenHeader
      value: Authorization
auth:
  secretStore: local-secret-store
scopes:
  - payments
