name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  job:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install score-compose
        uses: score-spec/setup-score@v3
        with:
          file: score-compose
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
      - name: make deploy-local
        run: |
          make deploy-local
      #- name: make compose-test
      #  run: |
      #    make compose-test
      - name: make kind-create-cluster
        run: |
          make kind-create-cluster
      - name: make kind-load-image
        run: |
          make kind-load-image
      - name: install score-k8s
        uses: score-spec/setup-score@v3
        with:
          file: score-k8s
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
      - name: make deploy-development
        id: deploy-development
        run: |
          make deploy-development